

[libe-ukraine]
title = "Libération Tag Ukraine"
url = "https://www.liberation.fr/tags/ukraine/"
entrySelector = ".left-article-section .custom-card-list article"
titleSelector = ".col-sm-xl-12 h2"
linkSelector = ".col-sm-xl-12 a.color_grey_4"
contentSelector= ".col-sm-xl-12 p.description-text"
